### ISSUE TITLE
Remove stateChangeTrigger when object is deleted

### ISSUE THREAD

**Issue by klein0r** [Apollon77/iobroker-tools#41]
The handler is not removed from the ``stateChangeTrigger`` list when ``deleteObject`` is called.

https://github.com/Apollon77/iobroker-tools/blob/1581c3e2427dc4425dfa8ec8a9780791bca4e02a/lib/objectHelper.js#L121-L127

**Comment by Apollon77** [comment]
Good catch, will fix after vacation

**Comment by Apollon77** [comment]
fixed by 0.2.1
